# OpenRASP-IAST 默认配置文件模板, 不要在这里修改配置

# 预处理模块
preprocessor.http_port: 25931                        # http服务监听端口
preprocessor.process_num: 2                          # http服务进程数
preprocessor.request_lru_size: 1000                  # 每个进程的每个扫描目标对应一个LRU，总大小: 进程数 * 扫描目标数 * lru_size
preprocessor.api_path: /openrasp-result              # OpenRASP iast插件发送数据的目标 url path
preprocessor.max_buffer_size: 104857600              # http服务器接受数据的缓冲区大小, 单位Bytes, 默认100M
preprocessor.plugin_name: default                    # 使用的去重插件名

# 预处理模块
monitor.schedule_interval: 1.000                      # 扫描速率自动调整策略执行间隔
monitor.max_cpu: 80                                   # cpu使用率超过限制会降低并发扫描速率
monitor.min_cpu: 50                                   # cpu使用率低于该值会增加并发扫描速率
monitor.console_port: 18664                           # 管理后台端口

# 扫描配置
scanner.max_concurrent_request: 5                    # 最大扫描并发线程数
scanner.min_request_interval: 20                       # 每个线程最小扫描请求间隔(ms)
scanner.max_request_interval: 1000                    # 每个线程最大扫描请求间隔(ms)
scanner.request_timeout: 5                            # 扫描请求超时时间(s)
scanner.retry_times: 3                                # 扫描请求失败重试次数
scanner.max_module_instance: 16                       # 最大扫描任务数量

# 云控配置
cloud_api.enable: True                                # 是否上传结果到云控
cloud_api.backend_url: "http://rasp-cloud:8086"             # 云控地址
cloud_api.app_secret: "vqxSEmNq81z1M9kSfEmJGS5vLMMqyWdfOkioXY4lgbo"                        # 云控secret_key
cloud_api.app_id: "e0aba6ee81472031d3a6f8d3acea508e83aa044e"                                # 云控app_id

# 绑定核心(仅支持linux)
affinity.enable: false                                # 是否以绑定CPU核心的方式运行
affinity.core_num: 2                                  # 绑定的核心数量

# 日志配置
log.level: DEBUG                                       # log级别，可选: DEBUG INFO WARNING ERROR CRITICAL
log.path: "/root/openrasp-iast-logs/"                                       # log文件路径, 为空时使用 /home/user/openrasp-iast/log
log.rotate_size: 5                                    # 触发rotate的日志大小，单位MB
log.rotate_num: 2                                     # rotate文件最多保存份数不包括当前日志文件

# MySQL 配置
database.host: 'mysql5.6'                              # 数据库地址
database.port: 3306                                   # 端口
database.username: rasp                               # 连接用户名
database.password: 'rasp123'                                 # 连接密码
database.db_name: openrasp                       # 数据库名

